# Generated by Django 6.0.1 on 2026-01-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_source_income_income_title_income_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='expense_title',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='price',
        ),
    ]
